<?xml version="1.0"?>
<package format="3">
  <name>scout_description</name>
  <version>0.4.2</version>
  <description>AgileX Scout Husky URDF description</description>

  <author email="rgariepy@clearpathrobotics.com">Ryan Gariepy</author>
  <author email="pmukherj@clearpathrobotics.com">Prasenjit Mukherjee</author>
  <author email="mpurvis@clearpathrobotics.com">Mike Purvis</author>
  <author email="paul@bovbel.com">Paul Bovbel</author>
  <author email="dash@clearpathrobotics.com">Devon Ash</author>

  <maintainer email="paul@bovbel.com">Paul Bovbel</maintainer>
  <maintainer email="tbaltovski@clearpathrobotics.com">Tony Baltovski</maintainer>

  <url type="website">http://ros.org/wiki/scout_description</url>
  <url type="bugtracker">https://github.com/husky/husky/issues</url>
  <url type="repository">https://github.com/husky/husky</url>

  <license>BSD</license>

  <depend>diff_drive_controller</depend>
  <depend>ros2_controllers</depend>
  <depend>ros2_control</depend>
  <depend>gz_ros2_control</depend>

  <exec_depend>urdf</exec_depend>
  <exec_depend>xacro</exec_depend>
  <!-- <exec_depend>lms1xx</exec_depend> -->

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
