controller_manager:
  ros__parameters:
    update_rate: 100
    wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

wheel_velocity_controller:
  ros__parameters:
    joints:
      - front_left_wheel
      - rear_left_wheel
      - front_right_wheel
      - rear_right_wheel
    interface_name: velocity
